//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constant {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constant() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Constant", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Dropbox Account.
        /// </summary>
        internal static string BACK_DROPBOX {
            get {
                return ResourceManager.GetString("BACK_DROPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Exact Online Account.
        /// </summary>
        internal static string BACK_EXACTONLINE {
            get {
                return ResourceManager.GetString("BACK_EXACTONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate with Dropbox.
        /// </summary>
        internal static string CONNECT_DROPBOX {
            get {
                return ResourceManager.GetString("CONNECT_DROPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate with Exact Online.
        /// </summary>
        internal static string CONNECT_EXACTONLINE {
            get {
                return ResourceManager.GetString("CONNECT_EXACTONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user account.
        /// </summary>
        internal static string CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Dropbox.
        /// </summary>
        internal static string DISCONNECT_DROPBOX {
            get {
                return ResourceManager.GetString("DISCONNECT_DROPBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Exact Online.
        /// </summary>
        internal static string DISCONNECT_EXACTONLINE {
            get {
                return ResourceManager.GetString("DISCONNECT_EXACTONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox Account.
        /// </summary>
        internal static string DROPBOX_ACCOUNT {
            get {
                return ResourceManager.GetString("DROPBOX_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox Account Info.
        /// </summary>
        internal static string DROPBOX_ACCOUNT_INFO {
            get {
                return ResourceManager.GetString("DROPBOX_ACCOUNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to connect with your Dropbox.
        /// </summary>
        internal static string DROPBOX_CONNECT_FAIL {
            get {
                return ResourceManager.GetString("DROPBOX_CONNECT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connect with your Dropbox.
        /// </summary>
        internal static string DROPBOX_CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("DROPBOX_CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EMAIL_ADDR {
            get {
                return ResourceManager.GetString("EMAIL_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-site request forgery detected.
        /// </summary>
        internal static string ERR_CSRF {
            get {
                return ResourceManager.GetString("ERR_CSRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response code.
        /// </summary>
        internal static string ERR_RESP_CODE {
            get {
                return ResourceManager.GetString("ERR_RESP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Online Account.
        /// </summary>
        internal static string EXACTONLINE_ACCOUNT {
            get {
                return ResourceManager.GetString("EXACTONLINE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact Online Account Info.
        /// </summary>
        internal static string EXACTONLINE_ACCOUNT_INFO {
            get {
                return ResourceManager.GetString("EXACTONLINE_ACCOUNT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to connect with your Exact Online.
        /// </summary>
        internal static string EXACTONLINE_CONNECT_FAIL {
            get {
                return ResourceManager.GetString("EXACTONLINE_CONNECT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connect with your Exact Online.
        /// </summary>
        internal static string EXACTONLINE_CONNECT_SUCCESS {
            get {
                return ResourceManager.GetString("EXACTONLINE_CONNECT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string FAIL {
            get {
                return ResourceManager.GetString("FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local user account to login.
        /// </summary>
        internal static string LOCAL_LOGIN {
            get {
                return ResourceManager.GetString("LOCAL_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a user account.
        /// </summary>
        internal static string LOGIN_LINK {
            get {
                return ResourceManager.GetString("LOGIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LOGOFF {
            get {
                return ResourceManager.GetString("LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string NO_RECORD_FOUND {
            get {
                return ResourceManager.GetString("NO_RECORD_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PAGE {
            get {
                return ResourceManager.GetString("PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string PAGE_OF {
            get {
                return ResourceManager.GetString("PAGE_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user account.
        /// </summary>
        internal static string REGISTER_LINK {
            get {
                return ResourceManager.GetString("REGISTER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string REMEMBER_ME {
            get {
                return ResourceManager.GetString("REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SIGNIN {
            get {
                return ResourceManager.GetString("SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync History.
        /// </summary>
        internal static string SYNC_HISTORY {
            get {
                return ResourceManager.GetString("SYNC_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync History Details.
        /// </summary>
        internal static string SYNC_HISTORY_DETAILS {
            get {
                return ResourceManager.GetString("SYNC_HISTORY_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated by user.
        /// </summary>
        internal static string TERMINATED_BY_USER {
            get {
                return ResourceManager.GetString("TERMINATED_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fail.
        /// </summary>
        internal static string TOTAL_FAIL {
            get {
                return ResourceManager.GetString("TOTAL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total File(s).
        /// </summary>
        internal static string TOTAL_FILES {
            get {
                return ResourceManager.GetString("TOTAL_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Success.
        /// </summary>
        internal static string TOTAL_SUCCESS {
            get {
                return ResourceManager.GetString("TOTAL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sync.
        /// </summary>
        internal static string TOTAL_SYNC {
            get {
                return ResourceManager.GetString("TOTAL_SYNC", resourceCulture);
            }
        }
    }
}
